Bug 7060
norm-l/odx pull request #183
Opened 2023-10-06 11:55 UTC by monalisasarkar123

Update the hidden text for the 'Change' & 'Remove' links

2023-10-06 12:14 UTC, AkhilaHMRC requested changes

2023-10-06 12:14 UTC, AkhilaHMRC commented on src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
> +  let itemName = "";
let itemName = (useType === 1) ? t('GDS_INFO_ITEM_CHILD') : '';

2023-10-09 09:13 UTC, monalisasarkar123 commented on src/components/custom-sdk/template/HMRC_ODX_GDSSummaryCard/index.tsx
> +  let itemName = "";
done

2023-10-09 09:20 UTC, AkhilaHMRC approved these changes

2023-10-09 09:21 UTC, merged