BUG-6776: Fixed error sequence issue on all screen except one
norm-l/odx pull request #277
Opened 2023-12-15 13:21 UTC by gautamkumar-hmrc

Sorting logic is not working properly because displayOrder is not correct when form elements are not coming on same level from pega. By removing sorting logic, we are able to fixed issue on all screens except one which require pega change.

2023-12-18 15:15 UTC, nickwhm approved these changes

2023-12-19 10:34 UTC, ModyGhaly reviewed
Hi @gautamkumar-hmrc Kindly please make sure your fix prettier and republish the branch after formatting. Thanks

2023-12-19 12:42 UTC, ModyGhaly approved these changes

2023-12-19 13:01 UTC, ModyGhaly requested changes
This Branch has a conflict >.. Please pull latest before you make your PR.  Thanks

2023-12-19 13:21 UTC, merged