Bug 6974 - Claimant unexpectedly returned to portal
norm-l/odx pull request #311
Opened 2024-01-12 17:48 UTC by nickwhm

The bug here is relates to using the app on mobile devices. When you change your language settings in the middle of a claim, for example to make sure the date is shown in the correct format in the browser, it refreshes the page. Because it does that it locks the user out of their current claim they are working on. I've added a beforeunload event to save the claim when it refreshes.

2024-01-15 13:48 UTC, gautamkumar-hmrc commented on src/components/override-sdk/infra/Assignment/Assignment.tsx
> +
This is duplicate logic as same is handled in DefaultForm.tsx. One of these need to be removed.

2024-01-18 11:49 UTC, nickwhm commented
Closed and re-raisning another PR

2024-01-24 16:53 UTC, AkhilaHMRC requested changes

2024-01-24 16:53 UTC, AkhilaHMRC commented on src/components/override-sdk/infra/Assignment/Assignment.tsx
> +          console.log(`"buttonPress:" ${sAction}, ${sButtonType}`);
remove the console log

2024-01-24 16:53 UTC, AkhilaHMRC commented on src/components/override-sdk/infra/Assignment/Assignment.tsx
> +    console.log(`"_onButtonPress:" ${sAction}, ${sButtonType}`);
remove console log

2024-02-08 18:10 UTC, closed without merging