Us 12030 - adding Timeout feature to unauth journey
norm-l/odx pull request #316
Opened 2024-01-17 16:28 UTC by SushreeM-h

- TimeoutPopup file has been split into 2, authTimeout and unauthTimeout
- refactored certain functions in index.tsx of both auth and unauth Chb folders
- most timeout related functions have been extracted out to timeOutUtils.tsx
- added the exit page after time out and data delete

Yet to add to pr ->
- how to know(for unauth journey) when the user chooses to Delete answers or when the session times out due to inactivity and the data is deleted; because the exit page is conditional to this.

2024-01-18 15:28 UTC, akshaykalaskar1 commented on src/samples/UnAuthChildBenefitsClaim/index.tsx
>  declare const myLoadMashup: any;
Please use type

2024-01-19 13:19 UTC, AkhilaHMRC requested changes

2024-01-19 13:19 UTC, AkhilaHMRC commented on src/components/AppComponents/TimeoutPopup/unauthTimeOut.tsx
> +          For your security
add the text content on this page to translation json, including the button labels

2024-01-19 13:19 UTC, AkhilaHMRC commented on src/samples/UnAuthChildBenefitsClaim/deleteAnswers.tsx
> +        <Button variant='start'>
Add the text content on this page to translation json

2024-01-19 13:19 UTC, AkhilaHMRC commented on src/samples/UnAuthChildBenefitsClaim/index.tsx
> +  const [, setAuthType] = useState('gg'); // authType
set the default authType from sdkConfig

2024-01-23 10:31 UTC, SushreeM-h commented on src/samples/UnAuthChildBenefitsClaim/index.tsx
>  declare const myLoadMashup: any;
done

2024-01-23 10:32 UTC, SushreeM-h commented on src/samples/UnAuthChildBenefitsClaim/index.tsx
> +  const [, setAuthType] = useState('gg'); // authType
removed it, because not used here.

2024-01-23 10:58 UTC, nickwhm commented on src/components/AppComponents/TimeoutPopup/timeOutUtils.tsx
> +let milisecondsTilWarning = 10 * 1000;
Maybe I don't understand something here but these seem quick for the timeouts, 10 seconds?

2024-01-23 11:08 UTC, gautamkumar-hmrc approved these changes

2024-01-23 11:11 UTC, Sasankachyuta13 approved these changes

2024-01-23 12:35 UTC, nickwhm approved these changes

2024-01-23 12:38 UTC, ModyGhaly approved these changes

2024-01-23 12:39 UTC, merged