Dt1 deployment autocomplete
norm-l/odx pull request #345
Opened 2024-01-30 11:59 UTC by monalisasarkar123

Has updated main branch and multi-name, multi-nationality and multi-country code added

2024-01-30 12:12 UTC, gautamkumar-hmrc approved these changes

2024-01-30 16:35 UTC, gautamkumar-hmrc approved these changes

2024-01-31 11:19 UTC, akshaykalaskar1 approved these changes

2024-02-05 13:07 UTC, akshaykalaskar1 requested changes

2024-02-05 13:07 UTC, akshaykalaskar1 commented on src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
> +  helper;
helper not needed?

2024-02-06 11:49 UTC, monalisasarkar123 commented on src/components/override-sdk/field/AutoComplete/AutoComplete.tsx
> +  helper;
removed

2024-02-06 11:59 UTC, akshaykalaskar1 approved these changes

2024-02-06 12:07 UTC, gautamkumar-hmrc approved these changes

2024-02-06 12:48 UTC, ModyGhaly approved these changes

2024-02-06 12:54 UTC, merged