Us 10226 4 - Apply - Claimant - Welsh Translation for claimant
norm-l/odx pull request #399
Opened 2024-03-07 14:56 UTC by monalisasarkar123

2024-03-08 15:32 UTC, gautamkumar-hmrc approved these changes

2024-03-11 09:12 UTC, Sasankachyuta13 approved these changes

2024-03-11 09:15 UTC, SushreeM-h approved these changes

2024-03-11 09:32 UTC, AkhilaHMRC requested changes

2024-03-11 09:32 UTC, AkhilaHMRC commented on assets/i18n/cy.json
> +  "CLOSE_CLAIM": "Cau’r hawliad",
this looks to be removed

2024-03-11 09:32 UTC, AkhilaHMRC commented on assets/i18n/cy.json
> +  "PRINT_THIS_INFO": "Argraffwch y dudalen hon neu gwnewch nodyn o’r cyfeirnod. Bydd angen hwn arnoch os byddwch yn cysylltu â CThEF neu os bydd CThEF yn gofyn am ragor o wybodaeth",
should there be dot at the end

2024-03-11 09:32 UTC, AkhilaHMRC commented on assets/i18n/cy.json
> +  "YOUR_FEEDBACK_HELPS_US_MAKES_OUR_SERVICE_BETTER": "Mae’ch adborth yn ein helpu i wella ein gwasanaeth.",
should the dot be removed at the end

2024-03-11 09:32 UTC, AkhilaHMRC commented on assets/i18n/cy.json
> +  "YOU_CAN_CREATE_A_PERSONAL_GOVT": "Os nad oes gennych gyfrif personol ar gyfer Porth y Llywodraeth, gallwch greu un.",
Should there be dot at the end

2024-03-11 09:46 UTC, monalisasarkar123 commented on assets/i18n/cy.json
> +  "CLOSE_CLAIM": "Cau’r hawliad",
done

2024-03-11 09:46 UTC, monalisasarkar123 commented on assets/i18n/cy.json
> +  "YOUR_FEEDBACK_HELPS_US_MAKES_OUR_SERVICE_BETTER": "Mae’ch adborth yn ein helpu i wella ein gwasanaeth.",
done

2024-03-11 10:07 UTC, merged