Us 10029 and 9829
norm-l/odx pull request #90
Opened 2023-07-11 10:16 UTC by SushreeM-h

- Service header and Sign out navlink added to the navbar
- Sign out link logs the user out and redirects to the required link

2023-07-11 13:33 UTC, peter-mal approved these changes

2023-07-11 14:59 UTC, AkhilaHMRC requested changes

2023-07-11 14:59 UTC, AkhilaHMRC commented on src/helpers/authManager.js
> +    console.log('logging out');
remove the console log

2023-07-11 15:05 UTC, SushreeM-h commented on src/helpers/authManager.js
> +    console.log('logging out');
Removed.

2023-07-12 11:07 UTC, AkhilaHMRC approved these changes

2023-07-12 11:07 UTC, merged